#!/bin/bash
rm shadow*.*
convert -background none -fill white -font MyriadPro-BlackSemiCn -pointsize 112 label:2 -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage -crop 65x91+7+0 shadow1.png
convert -background none -fill white -font MyriadPro-BlackSemiCn -pointsize 112 label:4 -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage -crop 61x91+4+0 shadow2.png
convert -background none -fill white -font PizzaDude-Stars -pointsize 30 label:t -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage -crop 23x36+7+0 shadow3.png
convert -background none -fill white -font MyriadPro-BlackSemiCn -pointsize 93 label:600 -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage -crop 153x80+7+0 shadow4.png
convert -background none -gravity South shadow*.* +append shadow.png
convert -background none -fill white -font MyriadPro-Bold -pointsize 42 label:'Комод' -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage shadow0.png
convert -background none -gravity East shadow0.png shadow.png -append 1.png
rm shadow*.*
convert -background none -fill white -font MyriadPro-BlackSemiCn -pointsize 112 label:3 -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage -crop 65x91+7+0 shadow1.png
convert -background none -fill white -font MyriadPro-BlackSemiCn -pointsize 112 label:4 -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage -crop 61x91+4+0 shadow2.png
convert -background none -fill white -font PizzaDude-Stars -pointsize 30 label:t -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage -crop 23x36+7+0 shadow3.png
convert -background none -fill white -font MyriadPro-BlackSemiCn -pointsize 93 label:600 -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage -crop 153x80+7+0 shadow4.png
convert -background none -gravity South shadow*.* +append shadow.png
convert -background none -fill white -font MyriadPro-Bold -pointsize 42 label:'Кровать ЮНОНА' -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage shadow0.png
convert -background none -gravity East shadow0.png shadow.png -append 2.png
rm shadow*.*
convert -background none -fill white -font MyriadPro-BlackSemiCn -pointsize 112 label:1 -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage -crop 65x91+7+0 shadow1.png
convert -background none -fill white -font MyriadPro-BlackSemiCn -pointsize 112 label:8 -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage -crop 61x91+4+0 shadow2.png
convert -background none -fill white -font PizzaDude-Stars -pointsize 30 label:t -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage -crop 23x36+7+0 shadow3.png
convert -background none -fill white -font MyriadPro-BlackSemiCn -pointsize 93 label:400 -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage -crop 153x80+7+0 shadow4.png
convert -background none -gravity South shadow*.* +append shadow.png
convert -background none -fill white -font MyriadPro-Bold -pointsize 42 label:'Тумба прикроват (2шт)' -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage shadow0.png
convert -background none -gravity East shadow0.png shadow.png -append 3.png
rm shadow*.*
convert -background none -fill white -font MyriadPro-BlackSemiCn -pointsize 112 label:9 -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage -crop 65x91+7+0 shadow1.png
convert -background none -fill white -font MyriadPro-BlackSemiCn -pointsize 112 label:8 -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage -crop 61x91+4+0 shadow2.png
convert -background none -fill white -font PizzaDude-Stars -pointsize 30 label:t -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage -crop 23x36+7+0 shadow3.png
convert -background none -fill white -font MyriadPro-BlackSemiCn -pointsize 93 label:200 -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage -crop 153x80+7+0 shadow4.png
convert -background none -gravity South shadow*.* +append shadow.png
convert -background none -fill white -font MyriadPro-Bold -pointsize 42 label:'Шкаф-купе 1470' -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage shadow0.png
convert -background none -gravity East shadow0.png shadow.png -append 4.png
