#!/bin/bash
convert -background none -fill white -font MyriadPro-BlackSemiCn -pointsize 112 label: -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage -crop 65x91+7+0 shadow1.png
convert -background none -fill white -font MyriadPro-BlackSemiCn -pointsize 112 label:9 -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage -crop 61x91+4+0 shadow2.png
convert -background none -fill white -font PizzaDude-Stars -pointsize 30 label:t -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage -crop 23x36+7+0 shadow3.png
convert -background none -fill white -font MyriadPro-BlackSemiCn -pointsize 93 label:990 -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage -crop 153x80+7+0 shadow4.png
convert -background none -gravity South shadow*.* +append shadow.png
convert -background none -fill white -font MyriadPro-Bold -pointsize 42 label:'Стенка МАКАРЕНА' -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage shadow0.png
convert -background none -gravity East shadow0.png shadow.png -append 16-21.png
rm shadow*.*
convert -background none -fill white -font MyriadPro-BlackSemiCn -pointsize 112 label:1 -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage -crop 65x91+7+0 shadow1.png
convert -background none -fill white -font MyriadPro-BlackSemiCn -pointsize 112 label:0 -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage -crop 61x91+4+0 shadow2.png
convert -background none -fill white -font PizzaDude-Stars -pointsize 30 label:t -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage -crop 23x36+7+0 shadow3.png
convert -background none -fill white -font MyriadPro-BlackSemiCn -pointsize 93 label:990 -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage -crop 153x80+7+0 shadow4.png
convert -background none -gravity South shadow*.* +append shadow.png
convert -background none -fill white -font MyriadPro-Bold -pointsize 42 label:'Стенка ФЛОРА' -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage shadow0.png
convert -background none -gravity East shadow0.png shadow.png -append 16-1.png
rm shadow*.*
convert -background none -fill white -font MyriadPro-BlackSemiCn -pointsize 112 label:1 -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage -crop 65x91+7+0 shadow1.png
convert -background none -fill white -font MyriadPro-BlackSemiCn -pointsize 112 label:0 -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage -crop 61x91+4+0 shadow2.png
convert -background none -fill white -font PizzaDude-Stars -pointsize 30 label:t -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage -crop 23x36+7+0 shadow3.png
convert -background none -fill white -font MyriadPro-BlackSemiCn -pointsize 93 label:800 -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage -crop 153x80+7+0 shadow4.png
convert -background none -gravity South shadow*.* +append shadow.png
convert -background none -fill white -font MyriadPro-Bold -pointsize 42 label:'Стенка МАКАРЕНА комби' -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage shadow0.png
convert -background none -gravity East shadow0.png shadow.png -append 16-2.png
rm shadow*.*
convert -background none -fill white -font MyriadPro-BlackSemiCn -pointsize 112 label:1 -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage -crop 65x91+7+0 shadow1.png
convert -background none -fill white -font MyriadPro-BlackSemiCn -pointsize 112 label:0 -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage -crop 61x91+4+0 shadow2.png
convert -background none -fill white -font PizzaDude-Stars -pointsize 30 label:t -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage -crop 23x36+7+0 shadow3.png
convert -background none -fill white -font MyriadPro-BlackSemiCn -pointsize 93 label:990 -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage -crop 153x80+7+0 shadow4.png
convert -background none -gravity South shadow*.* +append shadow.png
convert -background none -fill white -font MyriadPro-Bold -pointsize 42 label:'Стенка АЛЬФА' -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage shadow0.png
convert -background none -gravity East shadow0.png shadow.png -append 16-3.png
rm shadow*.*
convert -background none -fill white -font MyriadPro-BlackSemiCn -pointsize 112 label: -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage -crop 65x91+7+0 shadow1.png
convert -background none -fill white -font MyriadPro-BlackSemiCn -pointsize 112 label:7 -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage -crop 61x91+4+0 shadow2.png
convert -background none -fill white -font PizzaDude-Stars -pointsize 30 label:t -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage -crop 23x36+7+0 shadow3.png
convert -background none -fill white -font MyriadPro-BlackSemiCn -pointsize 93 label:990 -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage -crop 153x80+7+0 shadow4.png
convert -background none -gravity South shadow*.* +append shadow.png
convert -background none -fill white -font MyriadPro-Bold -pointsize 42 label:'Стенка ЛАТТЕ' -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage shadow0.png
convert -background none -gravity East shadow0.png shadow.png -append 16-4.png
rm shadow*.*
convert -background none -fill white -font MyriadPro-BlackSemiCn -pointsize 112 label: -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage -crop 65x91+7+0 shadow1.png
convert -background none -fill white -font MyriadPro-BlackSemiCn -pointsize 112 label:7 -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage -crop 61x91+4+0 shadow2.png
convert -background none -fill white -font PizzaDude-Stars -pointsize 30 label:t -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage -crop 23x36+7+0 shadow3.png
convert -background none -fill white -font MyriadPro-BlackSemiCn -pointsize 93 label:900 -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage -crop 153x80+7+0 shadow4.png
convert -background none -gravity South shadow*.* +append shadow.png
convert -background none -fill white -font MyriadPro-Bold -pointsize 42 label:'Стенка БЛЮЗ' -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage shadow0.png
convert -background none -gravity East shadow0.png shadow.png -append 16-5.png
rm shadow*.*
convert -background none -fill white -font MyriadPro-BlackSemiCn -pointsize 112 label: -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage -crop 65x91+7+0 shadow1.png
convert -background none -fill white -font MyriadPro-BlackSemiCn -pointsize 112 label:7 -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage -crop 61x91+4+0 shadow2.png
convert -background none -fill white -font PizzaDude-Stars -pointsize 30 label:t -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage -crop 23x36+7+0 shadow3.png
convert -background none -fill white -font MyriadPro-BlackSemiCn -pointsize 93 label:250 -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage -crop 153x80+7+0 shadow4.png
convert -background none -gravity South shadow*.* +append shadow.png
convert -background none -fill white -font MyriadPro-Bold -pointsize 42 label:'Шкаф ШК-205 (1.38м)' -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage shadow0.png
convert -background none -gravity East shadow0.png shadow.png -append 16-6.png
rm shadow*.*
convert -background none -fill white -font MyriadPro-BlackSemiCn -pointsize 112 label: -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage -crop 65x91+7+0 shadow1.png
convert -background none -fill white -font MyriadPro-BlackSemiCn -pointsize 112 label:7 -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage -crop 61x91+4+0 shadow2.png
convert -background none -fill white -font PizzaDude-Stars -pointsize 30 label:t -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage -crop 23x36+7+0 shadow3.png
convert -background none -fill white -font MyriadPro-BlackSemiCn -pointsize 93 label:250 -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage -crop 153x80+7+0 shadow4.png
convert -background none -gravity South shadow*.* +append shadow.png
convert -background none -fill white -font MyriadPro-Bold -pointsize 42 label:'Шкаф ШК-203 (1.38м)' -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage shadow0.png
convert -background none -gravity East shadow0.png shadow.png -append 16-7.png
rm shadow*.*
convert -background none -fill white -font MyriadPro-BlackSemiCn -pointsize 112 label: -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage -crop 65x91+7+0 shadow1.png
convert -background none -fill white -font MyriadPro-BlackSemiCn -pointsize 112 label:4 -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage -crop 61x91+4+0 shadow2.png
convert -background none -fill white -font PizzaDude-Stars -pointsize 30 label:t -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage -crop 23x36+7+0 shadow3.png
convert -background none -fill white -font MyriadPro-BlackSemiCn -pointsize 93 label:900 -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage -crop 153x80+7+0 shadow4.png
convert -background none -gravity South shadow*.* +append shadow.png
convert -background none -fill white -font MyriadPro-Bold -pointsize 42 label:'Шкаф ШК-204 (0.92м)' -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage shadow0.png
convert -background none -gravity East shadow0.png shadow.png -append 16-8.png
rm shadow*.*
convert -background none -fill white -font MyriadPro-BlackSemiCn -pointsize 112 label: -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage -crop 65x91+7+0 shadow1.png
convert -background none -fill white -font MyriadPro-BlackSemiCn -pointsize 112 label:4 -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage -crop 61x91+4+0 shadow2.png
convert -background none -fill white -font PizzaDude-Stars -pointsize 30 label:t -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage -crop 23x36+7+0 shadow3.png
convert -background none -fill white -font MyriadPro-BlackSemiCn -pointsize 93 label:500 -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage -crop 153x80+7+0 shadow4.png
convert -background none -gravity South shadow*.* +append shadow.png
convert -background none -fill white -font MyriadPro-Bold -pointsize 42 label:'Шкаф ШК-202 (0.92м)' -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage shadow0.png
convert -background none -gravity East shadow0.png shadow.png -append 16-9.png
rm shadow*.*
convert -background none -fill white -font MyriadPro-BlackSemiCn -pointsize 112 label: -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage -crop 65x91+7+0 shadow1.png
convert -background none -fill white -font MyriadPro-BlackSemiCn -pointsize 112 label:4 -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage -crop 61x91+4+0 shadow2.png
convert -background none -fill white -font PizzaDude-Stars -pointsize 30 label:t -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage -crop 23x36+7+0 shadow3.png
convert -background none -fill white -font MyriadPro-BlackSemiCn -pointsize 93 label:990 -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage -crop 153x80+7+0 shadow4.png
convert -background none -gravity South shadow*.* +append shadow.png
convert -background none -fill white -font MyriadPro-Bold -pointsize 42 label:'Шкаф ШК-206 (0.92м)' -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage shadow0.png
convert -background none -gravity East shadow0.png shadow.png -append 16-10.png
rm shadow*.*
convert -background none -fill white -font MyriadPro-BlackSemiCn -pointsize 112 label:1 -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage -crop 65x91+7+0 shadow1.png
convert -background none -fill white -font MyriadPro-BlackSemiCn -pointsize 112 label:0 -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage -crop 61x91+4+0 shadow2.png
convert -background none -fill white -font PizzaDude-Stars -pointsize 30 label:t -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage -crop 23x36+7+0 shadow3.png
convert -background none -fill white -font MyriadPro-BlackSemiCn -pointsize 93 label:800 -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage -crop 153x80+7+0 shadow4.png
convert -background none -gravity South shadow*.* +append shadow.png
convert -background none -fill white -font MyriadPro-Bold -pointsize 42 label:'Кухня РАДУГА-2,0' -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage shadow0.png
convert -background none -gravity East shadow0.png shadow.png -append 16-11.png
rm shadow*.*
convert -background none -fill white -font MyriadPro-BlackSemiCn -pointsize 112 label:1 -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage -crop 65x91+7+0 shadow1.png
convert -background none -fill white -font MyriadPro-BlackSemiCn -pointsize 112 label:2 -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage -crop 61x91+4+0 shadow2.png
convert -background none -fill white -font PizzaDude-Stars -pointsize 30 label:t -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage -crop 23x36+7+0 shadow3.png
convert -background none -fill white -font MyriadPro-BlackSemiCn -pointsize 93 label:900 -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage -crop 153x80+7+0 shadow4.png
convert -background none -gravity South shadow*.* +append shadow.png
convert -background none -fill white -font MyriadPro-Bold -pointsize 42 label:'Кухня РАДУГА-2,6' -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage shadow0.png
convert -background none -gravity East shadow0.png shadow.png -append 16-12.png
rm shadow*.*
convert -background none -fill white -font MyriadPro-BlackSemiCn -pointsize 112 label: -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage -crop 65x91+7+0 shadow1.png
convert -background none -fill white -font MyriadPro-BlackSemiCn -pointsize 112 label:9 -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage -crop 61x91+4+0 shadow2.png
convert -background none -fill white -font PizzaDude-Stars -pointsize 30 label:t -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage -crop 23x36+7+0 shadow3.png
convert -background none -fill white -font MyriadPro-BlackSemiCn -pointsize 93 label:900 -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage -crop 153x80+7+0 shadow4.png
convert -background none -gravity South shadow*.* +append shadow.png
convert -background none -fill white -font MyriadPro-Bold -pointsize 42 label:'Кухня ФОТОПЕЧАТЬ-1,5' -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage shadow0.png
convert -background none -gravity East shadow0.png shadow.png -append 16-13.png
rm shadow*.*
convert -background none -fill white -font MyriadPro-BlackSemiCn -pointsize 112 label:1 -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage -crop 65x91+7+0 shadow1.png
convert -background none -fill white -font MyriadPro-BlackSemiCn -pointsize 112 label:1 -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage -crop 61x91+4+0 shadow2.png
convert -background none -fill white -font PizzaDude-Stars -pointsize 30 label:t -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage -crop 23x36+7+0 shadow3.png
convert -background none -fill white -font MyriadPro-BlackSemiCn -pointsize 93 label:700 -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage -crop 153x80+7+0 shadow4.png
convert -background none -gravity South shadow*.* +append shadow.png
convert -background none -fill white -font MyriadPro-Bold -pointsize 42 label:'Кухня ФОТОПЕЧАТЬ-2,0' -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage shadow0.png
convert -background none -gravity East shadow0.png shadow.png -append 16-14.png
rm shadow*.*
