#!/bin/bash
rm *.png
convert -background none -fill white -font My-Font-Regular -pointsize 112 label:8 -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage -crop 65x110+7+0 shadow1.png
convert -background none -fill white -font My-Font-Regular -pointsize 112 label:4 -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage -crop 65x110+4+0 shadow2.png
convert -background none -fill white -font My-Font-Regular -pointsize 80 label:. -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage -crop 20x0+7+0 shadow3.png
convert -background none -fill white -font My-Font-Regular -pointsize 90 label:967 -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage -crop 165x95+7+0 shadow4.png
convert -background none -gravity South shadow*.* +append price.png
rm shadow*.*
convert -background none -fill white -font BebasNeueBook -pointsize 100 label:'спальня уют' -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage shadow1.png
convert -background none -fill white -font HelveticaNeueCyr-Light -pointsize 33 label:'Шкаф 4х ств., кровать 160, комод, 2 тумбы' -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage shadow3.png
convert -background none -gravity West shadow*.* -append k0.png
rm shadow*.*
