#!/bin/bash
convert 1200001_0.jpg -gravity SouthWest -fill '#ffffff' -box '#6633ffd0' -font Impact -pointsize 40 -annotate 0 ' Прихожая Ева ' 1200001_0.jpg
convert 1200001_0.jpg -fill '#ffffff' -box '#6633ffc0' -font Droid-Sans -pointsize 25 -annotate +135+840 ' 21 000 тг.' 1200001_0.jpg
convert 1030002_0.jpg -gravity SouthWest -fill '#ffffff' -box '#6633ffd0' -font Impact -pointsize 40 -annotate 0 ' Спальня Винтаж ' 1030002_0.jpg
convert 1030002_0.jpg -fill '#ffffff' -box '#6633ffc0' -font Droid-Sans -pointsize 25 -annotate +275+830 ' 17 200 тг.' 1030002_0.jpg
convert 3100003_3.jpg -gravity SouthWest -fill '#ffffff' -box '#6633ffd0' -font Impact -pointsize 30 -annotate 0 ' Спальня Модерн ' 3100003_3.jpg
convert 3100003_3.jpg -fill '#ffffff' -box '#6633ffc0' -font Droid-Sans -pointsize 25 -annotate +150+445 ' 50 000 ' 3100003_3.jpg
convert 3100003_3.jpg -fill '#ffffff' -box '#6633ffc0' -font Droid-Sans -pointsize 25 -annotate +245+445 ' 52 800 ' 3100003_3.jpg
convert 3100003_3.jpg -fill '#ffffff' -box '#6633ffc0' -font Droid-Sans -pointsize 25 -annotate +340+445 ' 55 000 ' 3100003_3.jpg
convert 3100003_3.jpg -fill '#ffffff' -box '#6633ffc0' -font Droid-Sans -pointsize 25 -annotate +435+445 ' 57 200 тг.' 3100003_3.jpg
convert 3100006_2.jpg -gravity SouthWest -fill '#ffffff' -box '#6633ffd0' -font Impact -pointsize 40 -annotate 0 ' Спальня Фиеста ' 3100006_2.jpg
convert 3100006_2.jpg -fill '#ffffff' -box '#6633ffc0' -font Droid-Sans -pointsize 25 -annotate +40+825 ' 32 800 тг.' 3100006_2.jpg
